return {
  {
    "mrjones2014/smart-splits.nvim",
    opts = {
      at_edge = "stop",
    },
    keys = {
      {
        "<c-h>",
        function()
          require("smart-splits").move_cursor_left()
        end,
      },
      {
        "<c-j>",
        function()
          require("smart-splits").move_cursor_down()
        end,
      },
      {
        "<c-k>",
        function()
          require("smart-splits").move_cursor_up()
        end,
      },
      {
        "<c-l>",
        function()
          require("smart-splits").move_cursor_right()
        end,
      },
      {
        "<c-up>",
        function()
          require("smart-splits").resize_up()
        end,
      },
      {
        "<c-down>",
        function()
          require("smart-splits").resize_down()
        end,
      },
      {
        "<c-left>",
        function()
          require("smart-splits").resize_left()
        end,
      },
      {
        "<c-right>",
        function()
          require("smart-splits").resize_right()
        end,
      },
    },
  },
}
